
spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/apple?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    url: jdbc:mysql://root:nsonPiIbzvynTYYecyPShqverExxqOgj@autorack.proxy.rlwy.net:41936/railway
    username: root
#    password: ${MYSQL_ROOT_PASSWORD:checkra1n}
    password: nsonPiIbzvynTYYecyPShqverExxqOgj
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
#      ddl-auto: none # No automatic schema updates (use 'update', 'create', 'create-drop', or 'none' as per your need)
      ddl-auto: update
    show-sql: true # Show SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Specify MySQL 8 dialect for Hibernate

  # Enable multipart file upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Secret Configuration
jwt:
  secret: nguyennpcoderJWTabcdefghijklmnoabcdefghijk # JWT secret key used for signing the tokens

logging:
  level:
    org.springframework.security: DEBUG  # Enable detailed Spring Security logs
#server:
#  port: 8899
